### ISSUE TITLE
BE: Adicionar pdm

### ISSUE THREAD

**Issue by ivancrneto** [gogixweb/bahea-cal#20]
Usar PDM (https://pdm-project.org/latest/) para gerenciar os requirements do projeto.

* Instalar o PDM
* Inicializar as configurações (`pdm init django`)
* Preencher o pyproject.toml
* Gerar os requirements.txt e requirements-dev.txt

## Aceitação
1. PDM está instalado e é utilizado para gerenciar as dependências do projeto

**Comment by ruanclaudio** [comment]
PDM seria Product Manager Data? O que é pretendido fazer com a adição do PDM?

**Comment by ivancrneto** [comment]
@ruanclaudio @Kauannery vejam se tá claro agora

**Comment by Kauannery** [comment]
Tem um outro ticket com pyproject.toml, aquele que estavamos fazendo, no caso aquela tarefa ficaria dentro dessa?
