### ISSUE TITLE
Adicionar codecov

### ISSUE THREAD

**Issue by ivancrneto** [gogixweb/bahea-cal#21]
Depende de: #33 e #34 

Adicionar Codecov.io no repositório (https://about.codecov.io/)

## Aceitação
1. Codecov está configurado e roda a cada PR

**Comment by Kauannery** [comment]
Qual codecov? o que seria?

**Comment by ruanclaudio** [comment]
Não entendi muito bem de qual maneira isso pode ser feito. O que seria esse codecov?
