### ISSUE TITLE
FE: Pesquisar como fazer o fluxo do Google Calendar no front-end

### ISSUE THREAD

**Issue by ivancrneto** [gogixweb/bahea-cal#22]
Esta tarefa consiste em procurar uma biblioteca e utilizá-la no projeto para que o processo de autorização do usuário no Google Calendar ocorra no front-end.

## Aceitação
1. Biblioteca de front-end instalada e configurada
2. Fluxo funciona até o momento em que é necessário enviar dados para o back-end

**Comment by ruanclaudio** [comment]
Esse fluxo seria tornar possível a utilização do google calendar no proprio site? Onde possivelmente iria exibir as datas de quando iria ocorrer os jogos ou coisa assim?

**Comment by ivancrneto** [comment]
@ruanclaudio seria o fluxo de autenticação e autorização do usuário com o seu calendário.
