### ISSUE TITLE
FE: Fazer primeiro deploy do front-end

### ISSUE THREAD

**Issue by ivancrneto** [gogixweb/bahea-cal#23]
Configurar e realizar o deploy do front-end na Digital Ocean.

**Comment by ruanclaudio** [comment]
Esse deploy seria tornar a parte do front end "acessivel" ou "utilizavel" para um usuário final?

**Comment by ivancrneto** [comment]
@ruanclaudio exatamente

**Comment by ivancrneto** [comment]
https://app.staging.baheacal.gogix.dev/
